name: MVopt
dependencies:
  - python=3.10
  - numpy
  - opencv
  - pillow
  - scikit-image
  - matplotlib
  - pip
  - pip:
      - torch==2.8.0+cu128
      - torchvision==0.23.0+cu128
      - torchaudio==2.8.0+cu128
